#!/usr/bin/env python3
"""Build the browser visual data and live Krawall replay assets."""

from __future__ import annotations

import argparse
import base64
import gzip
from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parent))
from analyze_rom import DATA_BASE, DIRECTORY, read_assets, read_song  # noqa: E402
from extract_krawall import extract_runtime_assets  # noqa: E402


def b64(data: bytes) -> str:
    return base64.b64encode(data).decode("ascii")


def quoted_chunks(value: str, width: int = 4096) -> str:
    chunks = [value[index:index + width] for index in range(0, len(value), width)]
    return "\n  + ".join(repr(chunk) for chunk in chunks)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("rom", nargs="?", type=Path, default=Path("mc-virus.gba"))
    parser.add_argument("--data-out", type=Path, default=Path("mcvirus_data.js"))
    parser.add_argument("--module-out", type=Path, default=Path("Module0.krw"))
    parser.add_argument("--bank-out", type=Path, default=Path("mc-virus.gba.krb"))
    args = parser.parse_args()

    rom = args.rom.read_bytes()
    bank, module = extract_runtime_assets(rom)
    assets = read_assets(rom)
    song = read_song(rom)
    archive = rom[DATA_BASE:DIRECTORY]
    archive_gz = gzip.compress(archive, compresslevel=9, mtime=0)
    asset_rows = ",\n    ".join(
        f"[{asset.name!r},{asset.offset},{asset.size}]" for asset in assets
    )
    marker_rows = ",\n    ".join(
        f"[{marker.sample},{marker.value}]" for marker in song.markers
    )
    data_js = f"""// Generated by tools/build_data.py from mc-virus.gba.
// Derived archive bytes only: no ARM executable code is shipped to the browser.
export const MCV_EMBEDDED = {{
  archiveLength: {len(archive)},
  archiveGzipBase64: {quoted_chunks(b64(archive_gz))},
  assets: [
    {asset_rows}
  ],
  krawall: {{
    rate: 32768,
    tickSamples: {song.tick_samples},
    rowSamples: {song.row_samples},
    totalRows: {song.total_rows},
    markers: [
    {marker_rows}
    ]
  }}
}};
"""
    args.data_out.write_text(data_js)
    args.module_out.write_bytes(module)
    args.bank_out.write_bytes(bank)
    print(
        f"wrote {args.data_out} ({len(archive_gz)} compressed visual bytes), "
        f"{args.module_out} ({len(module)} module bytes), and "
        f"{args.bank_out} ({len(bank)} bank bytes)"
    )


if __name__ == "__main__":
    main()
